break up steps of visual regression test into branches depending on conditions

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -5,8 +5,20 @@ on:
     branch: [ "**" ]
 
 jobs:
+  check-commit:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check commit message
+        id: check_message
+        run: |
+          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
+          if [[ "$COMMIT_MESSAGE" == *"[ci skip]"* ]]; then
+            echo "CI skip commit detected, stopping workflow."
+            exit 0
+          fi
   lint:
     runs-on: ubuntu-latest
+    needs: check-commit
     steps:
       - uses: actions/checkout@v4
       - name: Use Node.js 20
@@ -19,6 +31,7 @@ jobs:
         run: npm run lint --fix-dry-run .
   test-jest:
     runs-on: ubuntu-latest
+    needs: check-commit
     steps:
       - uses: actions/checkout@v4
       - name: Use Node.js 20
@@ -31,6 +44,7 @@ jobs:
         run: npm run test
   test-storybook:
     runs-on: ubuntu-latest
+    needs: check-commit
     steps:
       - uses: actions/checkout@v4
       - name: Use Node.js 20
@@ -48,6 +62,7 @@ jobs:
       - name: Run Storybook tests
         run: npm run test:storybook
   test-visual:
+    needs: check-commit
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -59,12 +74,80 @@ jobs:
         run: npm ci
       - name: Install Playwright
         run: npx playwright install --with-deps
-      - name: Start Storybook 
-        run: npm run storybook -- --ci --port 6006 &
-      - name: Wait for Storybook
-        run: npx wait-on http://localhost:6006
-      - name: Run Playwright test
-        run: npx playwright test
+      - name: Run visual regression test
+        run: |
+          npx playwright test || echo "Playwright test failed" >> $GITHUB_ENV
+
+      # Handling success case for any branch
+      # We are accepting the current generated image as the new baseline image for future comparisons
+      - name: Handle success
+        if: success()
+        run: |
+          for file in __test__/visual/images/*-current.png; do
+            mv "$file" "${file/-current.png/-baseline.png}"
+          done
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git add __test__/visual/images/*-baseline.png
+          git commit -m "Update Playwright baseline images [ci skip]"
+          git push
+
+      # Handling failure case for feature branches
+      # We persist all three images for the branch owner to review
+      - name: Handle feature branch failure
+        if: failure() && github.ref != "refs/heads/main"
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git add __test__/visual/images/*.png
+          git commit -m "Add Playwright test artifacts [ci skip]"
+          git push
+      - name: Comment on PR
+        if: failure() && github.ref != "refs/heads/main"
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          repository: ${{ github.repository }}
+          issue-number: ${{ github.event.pull_request.number }}
+          # body: "Visual regression test failed. Check the screenshots [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})."
+          body: "Visual regression test failed. Check the screenshots."
+
+      # Handling failure case for the main branch
+      - name: Handle main branch failure
+        if: failure() && github.ref == "refs/heads/main"
+        run: |
+          for file in __test__/visual/images/*-current.png; do
+            mv "$file" "${file/-current.png/-baseline.png}"
+          done
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git add __test__/visual/images/*-baseline.png
+          git commit -m "Update Playwright baseline images [ci skip]"
+          git push
+
+
+  # this works, but needs to be rewritten to account for different workflow results
+  # test-visual:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Use Node.js 20
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 20
+  #     - name: Install dependencies
+  #       run: npm ci
+  #     - name: Install Playwright
+  #       run: npx playwright install --with-deps
+  #     - name: Start Storybook 
+  #       run: npm run storybook -- --ci --port 6006 &
+  #     - name: Wait for Storybook
+  #       run: npx wait-on http://localhost:6006
+  #     - name: Run Playwright test
+  #       run: npx playwright test
+
+
+      # This works to save images to the branch
       # - uses: actions/upload-artifact@v4
       #   with:
       #     path: __test__/visual/**/screenshots/
